/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.citizen.id;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class Main extends Application {

		Button btn;
		int clicked = 0;
		String[] labels = {
						"Not yet clicked", "Clicked"};

		@Override
		public void start(Stage primaryStage) {
				btn = new Button();
				btn.setText( "Click me");
				btn.setOnAction( e -> buttonOnClick());

				BorderPane pane = new BorderPane();
				pane.setCenter( btn);

				int height = 700;
				int width = (int)(height * 1.618);
				Scene scene = new Scene( pane, width, height);

				primaryStage.setScene( scene);
				primaryStage.setTitle( "The Click Me App");
				primaryStage.show();
		}

		private void buttonOnClick() {
				clicked ^= 1;
				btn.setText( labels[clicked]);
		}
}
