/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.citizen.id;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

import java.io.IOException;

public class Main extends Application {

    @Override
    public void start(Stage primaryStage) throws IOException {
        Parent pane = FXMLLoader.load(getClass().getResource("main.fxml"));

        int height = 700;
        int width = (int) (height * 1.618);
        Scene scene = new Scene(pane, width, height);

        primaryStage.setScene(scene);
        primaryStage.setTitle("The Click Me App");
        primaryStage.show();
    }
}
